name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ruff
      run: python -m pip install --upgrade pip ruff

    - name: Run Ruff
      run: |
        ruff check --config ruff.toml

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure Commandline
      run: |
        curl -o allure-commandline.zip -L "https://github.com/allure-framework/allure2/releases/download/2.32.2/allure-2.32.2.zip"
        unzip allure-commandline.zip
        sudo mv allure-2.32.2 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest -n 3 -s --tb=short --disable-warnings --junitxml=report.xml --alluredir=allure-results
      continue-on-error: true

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
